apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-replicas-2
  annotations:
    storageclass.kubernetes.io/is-default-class: "true" # Make it default
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  fromBackup: ""
reclaimPolicy: Retain # Do not delete PV if PVC deleted
volumeBindingMode: Immediate
