apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-password
  namespace: postgresql
spec:
  encryptedData:
    password: AgBAFy6k3S/cdb5CkBDdpMOBEwOltj3qvcNB588Trfy16UuiINSqeDGVvzw6iRneQ5E+ZoNS+qVrweoFknZZjEW+Mg9PC+2siO7DLwsWIep4yzLjZy0Jg5qxX+yQX4DoM2MpznQvI0QxaMTReg/YKashykFSoXbgGsfRdMjsOLcZNNgVIV5PnMhkfWxWNJ2tironApkvEOLRr1XbVkckcIxLXx+fNDHHsT39m+TZHP0IUByKJEIws3TynlYgcxfkK9jtDU8+2ran7RnKosIKg+nqIdUqcbK1wv6+7kx13158TvkiNfmTqOpjuwkhRZnetsxbJWnQU+qH98mbbNHWPRUilIcm7R6Wu663TkGjV+rlAlUBcjrhEUWkH9ULr0XFkPcsJdv1gpIcyLhOSLm0c8MeqSPE2li9i/zVAzHa5D1Exu7jWYz64a8fnebSCsIHUZ39KwXk75H2/f3SytvXPuKpaJ6g/rfQ817FYdVyKQpJTDX/mo0hhCLAAd9AqvsTCWX3J+xq69Zr6jhOUxeh/ysFbACn2xelsOVvyMdJ8APJclNuEJbwIH7o8ywXXmzCYyU+TnwMEjsH5bzKbf37IwdkFC8bd0Ujx81aApLy1d01peWyE5ZqYkFtprvoHuVM2+LsQHHlyA+T8fxCk+6IGMK0qakUmusXy/dZajbCY0NmH6vU21i6IgwUf9ksNJE4tnemhott3+cmtftCgtK9SsMKWEU9eg==