primary:
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

auth:
  existingSecret: postgresql-password
  secretKeys:
    adminPasswordKey: "password"