---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-password
  namespace: postgresql
spec:
  encryptedData:
    password:
  template:
    metadata:
      name: postgresql-password
      namespace: postgresql
