apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/beeware17/k8s-learning.git
      targetRevision: apps
      path: apps/dev/longhorn
      ref: repo
    - chart: longhorn
      repoURL: https://charts.longhorn.io
      targetRevision: 1.8.1
      helm:
        releaseName: longhorn
        valueFiles:
          - $repo/apps/dev/longhorn/longhorn-helm-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
