apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/beeware17/k8s-learning.git
    targetRevision: dev
    path: apps/overlays/dev
    kustomize:
      enableHelm: true
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
