apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-dev
  namespace: argocd
annotations:
  argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://github.com/beeware17/k8s-learning.git
      targetRevision: apps
      path: apps/dev/postgresql
      ref: repo
    - chart: postgresql
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 16.6.3
      helm:
        releaseName: postgresql
        valueFiles:
          - $repo/apps/dev/postgresql/postgres-helm-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
